// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmM7AwrMa1XPAXSTMgfeiiyS3cck1CKg',
    appId: '1:569733014094:web:ca096e08e7b0f4869d191f',
    messagingSenderId: '569733014094',
    projectId: 'simpletaskapp-231f3',
    authDomain: 'simpletaskapp-231f3.firebaseapp.com',
    storageBucket: 'simpletaskapp-231f3.firebasestorage.app',
    measurementId: 'G-Q507SCQRTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4SwbpKl_2Mi-tM8N8Z3CRnr1hEUZLeU',
    appId: '1:569733014094:android:38afb617df7b2b879d191f',
    messagingSenderId: '569733014094',
    projectId: 'simpletaskapp-231f3',
    storageBucket: 'simpletaskapp-231f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq81lLk45GSrgtgUHZ0e9UDXRV-_Emko4',
    appId: '1:569733014094:ios:da2130b6b1f039bd9d191f',
    messagingSenderId: '569733014094',
    projectId: 'simpletaskapp-231f3',
    storageBucket: 'simpletaskapp-231f3.firebasestorage.app',
    iosBundleId: 'com.example.simpleTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq81lLk45GSrgtgUHZ0e9UDXRV-_Emko4',
    appId: '1:569733014094:ios:da2130b6b1f039bd9d191f',
    messagingSenderId: '569733014094',
    projectId: 'simpletaskapp-231f3',
    storageBucket: 'simpletaskapp-231f3.firebasestorage.app',
    iosBundleId: 'com.example.simpleTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmM7AwrMa1XPAXSTMgfeiiyS3cck1CKg',
    appId: '1:569733014094:web:07680bfb3aa223d49d191f',
    messagingSenderId: '569733014094',
    projectId: 'simpletaskapp-231f3',
    authDomain: 'simpletaskapp-231f3.firebaseapp.com',
    storageBucket: 'simpletaskapp-231f3.firebasestorage.app',
    measurementId: 'G-BKMXEKLEJV',
  );
}
